spring:
    application:
        name: insta
    datasource:
        url: "jdbc:mysql://localhost/instagram"
        username: "root"
        password: "9705"
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                dialect: org.hibernate.dialect.MySQL8Dialect
