spring:
  application:
    name: insta
  datasource:
    url: "jdbc:mysql://localhost/instagram"
    # url: "jdbc:/mysql://localhost:3306/instagram"
    username: "root"
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    # ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 10MB
      max-file-size: 10MB
